version: "3"

services:
    database:
        image: postgis/postgis
        ports:
            - "5432:5432"
        environment: 
            POSTGRES_DB: "mande"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "11111"
        volumes:
            - .:/docker-entrypoint-initdb.d