version: "3"

services: 
    frontend:
        build: ./cliente
        ports:
            - "3000:3000"
        environment: 
            CI: "true"
        depends_on: 
            - backend
    backend:
        build: ./Server
        ports:
            - "5000:5000"
        depends_on:
            - database
    database:
        image: mdillon/postgis
        ports:
            - "5432:5432"
        environment: 
            POSTGRES_DB: "mande"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "11111"
        volumes:
            - ./BD:/docker-entrypoint-initdb.d
